_ehVAMG_Remove0 	= (findDisplay 46) displayRemoveEventHandler ["keyDown",rgg_vamg_kd0];
_ehVAMG_Remove2 	= (findDisplay 46) displayRemoveEventHandler ["keyDown",rgg_vamg_kd1];
_ehVAMG_Remove3 	= (findDisplay 46) displayRemoveEventHandler ["keyDown",rgg_vamg_kd2];
_ehVAMG_Remove4 	= (findDisplay 46) displayRemoveEventHandler ["keyDown",rgg_vamg_kd3];
_ehVAMG_Remove5 	= (findDisplay 46) displayRemoveEventHandler ["keyDown",rgg_vamg_kd4];
_ehVAMG_Remove6 	= (findDisplay 46) displayRemoveEventHandler ["keyDown",rgg_vamg_kd5];
_ehVAMG_Remove7 	= (findDisplay 46) displayRemoveEventHandler ["keyDown",rgg_vamg_kd6];
_ehVAMG_Remove8 	= (findDisplay 46) displayRemoveEventHandler ["keyDown",rgg_vamg_kd7];
_ehVAMG_Remove9 	= (findDisplay 46) displayRemoveEventHandler ["keyDown",rgg_vamg_kd8];
_ehVAMG_Remove10 	= (findDisplay 46) displayRemoveEventHandler ["keyDown",rgg_vamg_kd9];
_ehVAMG_Remove11 	= (findDisplay 46) displayRemoveEventHandler ["keyDown",rgg_vamg_cnl];

VAMG_numericalInputbool = false;
vamp = false;

// 9 cutRsc ["default","PLAIN"];
// 10 cutRsc ["default","PLAIN"];
// 20 cutRsc ["default","PLAIN"];
// 30 cutRsc ["default","PLAIN"];
// 40 cutRsc ["default","PLAIN"];
// 50 cutRsc ["default","PLAIN"];
// 60 cutRsc ["default","PLAIN"];
// 70 cutRsc ["default","PLAIN"];
// 80 cutRsc ["default","PLAIN"];
// 90 cutRsc ["default","PLAIN"];
// 100 cutRsc ["default","PLAIN"];
// 110 cutRsc ["default","PLAIN"];
// 120 cutRsc ["default","PLAIN"];
// 130 cutRsc ["default","PLAIN"];
// 140 cutRsc ["default","PLAIN"];
// 150 cutRsc ["default","PLAIN"];
// 160 cutRsc ["default","PLAIN"];
// 170 cutRsc ["default","PLAIN"];
// 180 cutRsc ["default","PLAIN"];
// 200 cutRsc ["default","PLAIN"]; 
// 210 cutRsc ["default","PLAIN"]; 
// 211 cutRsc ["default","PLAIN"]; 
// 212 cutRsc ["default","PLAIN"]; 
// 213 cutRsc ["default","PLAIN"]; 
